### PR TITLE
Hotfix zh_cn for 1.20.1

### PR DESCRIPTION
**Pull request by ChuijkYahus**

### CODE REVIEW

**Comment by hjake123** [comment]
On this branch I've changed the entry `intro/techniques.md`, specifically the Litmus Paper section, to reflect the newly backported mechanics from 1.21. 

If we're doing a translation hotfix anyway, I'd like to get that retranslated as well, if that's ok!

**Comment by hjake123** [comment]
Also! I plan to fix the JEI integration by making the word " Power" translatable, since I noticed it is hardcoded right now. I'd like to store that word in `text.reactive.power`. There are many different Chinese words for this so I'd like to know which one you've been using to refer to alchemical Powers.

**Comment by hjake123** [comment]
Also! I realized that the JEI text saying "Power" wasn't translatable, so I've fixed that. That label is now found in `text.reactive.power` in the lang file. 

I think the word 能量 would be the best fit for that key based on what you've done before, but I'd like if you could confirm if having that word after a type of Power would make sense to readers the same way as something like "Mind Power" would in English.

**Comment by ChuijkYahus** [comment]
OK, would be done soon!

**Comment by ChuijkYahus** [comment]
> Also! I realized that the JEI text saying "Power" wasn't translatable, so I've fixed that. That label is now found in `text.reactive.power` in the lang file.
> 
> I think the word 能量 would be the best fit for that key based on what you've done before, but I'd like if you could confirm if having that word after a type of Power would make sense to readers the same way as something like "Mind Power" would in English.

It's better to have them attached. Names without "能量" is still understandable and has the same meaning, and was translated in such way at a few places. Though they're less explicit and preferable than names with it.

**Comment by ChuijkYahus** [comment]
I didn't find `text.reactive.power` in `en_us` tho, should it be like `%s Power` or just ` Power` only?

**Comment by hjake123** [comment]
Check the 1.21 branch, haven't added `text.reactive.power` to this one yet. 
It's " Power" in en_US so that the space is optional, but no need for a %s

EDIT: Ah, I hadn't pushed the commits either, that would probably help haha

**Comment by hjake123** [comment]
Also, thank you so much for your work here! You're actually only the second like contributor to one of my mods I've worked with ever so I am very grateful

**Comment by ChuijkYahus** [comment]
It's a great mod and I like the feel of figuring out mechanisms and explorations, keep up the great works! <3
I'll follow up translations from time to time also.

**Pull request merged**
